### ISSUE TITLE
repository-setup

### ISSUE THREAD

**Issue by HachemBouhadede** [202306-NEA-DZ-FEW/team-nine-capstone#1]
**Task title**
Repository Setup

**Task description**
use provided template, and update the workplace, match main and dev

**Subtasks**

- [x] update nextjs, react, eslint...etc

- [x] add tailwind with config

- [x] add team members

- [x] protect main and develop branches

**Comment by HachemBouhadede** [comment]
Completed, sorry for the repository mess
everything set, repository set for cloninig now
