### ISSUE TITLE
interests list for users 

### ISSUE THREAD

**Issue by HachemBouhadede** [202306-NEA-DZ-FEW/team-nine-capstone#34]
**Task title**
interrests list

**Task description**
allow user to select a number of interests from our interests list
this can also be added in the event

**Subtasks**

- [x] list interest inside the edit profile
- [x] make the list selective
- [x] push the interrests array to the data base

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/team-nine-capstone/assets/137968168/1b9ac7f2-b9fa-4274-b8e2-9d8fcfc5a82a)

**Link to the component on Figma**
Put the link here

**Comment by HachemBouhadede** [comment]
in addition to this, the interests are also available in the users profile

![image](https://github.com/202306-NEA-DZ-FEW/team-nine-capstone/assets/137968168/7bb96c01-e3b9-4c2d-94fd-43a3c357d118)

@Khalil-NOUI i tried to implement, the list and selectivity in the create event, and edit event pages, the way you implement the updated and document creation doesn't align with the way i went with for creating/editing the lists on my end, i'll have to change a lot in your code to do that, so i decided not to do that and leave it till further discussion

i use useState to manipulate field value initially, and fetch data (in the edition case i believe we have to) from database, only after that do i update the collection, meanwhile you're methode directly and always updates the docs
